### ISSUE TITLE
test with my own images

### ISSUE THREAD

**Issue by fjremnav** [tfzhou/ContrastiveSeg#11]
How do I run inference on my own images?

Thanks,

**Comment by tfzhou** [comment]
Hi, there is no inference script for testing a single image now. But I guess it will not be hard to do that.

**Comment by fjremnav** [comment]
@tfzhou 

It will be great if you can create one or provide a guidance of how to do it.

Thanks,

**Comment by tfzhou** [comment]
Hi @fjremnav , sorry for that I have no plan to write this script. It will be perfect if you would write it. The file may have a simple pipeline: 
```
# 1. define the model and load the pretrained weight
# 2. load the image using opencv
# 3. convert the image array to tensor with shape 1 x 3 x h x w
# 4. call the forward function of the model
```

you can also refer to [this line](https://github.com/tfzhou/ContrastiveSeg/blob/fa9ebe0cf04db92633d4ff481c1256e54edf1a2d/segmentor/tester.py#L310).
