### ISSUE TITLE
tsne

### ISSUE THREAD

**Issue by tahmine88** [tfzhou/ContrastiveSeg#12]
hi, how do you use tsne in a segmentation network to have such visualization?
thanks

**Comment by tahmine88** [comment]
that is my question too!

thanks in advance

**Comment by tfzhou** [comment]
Hi, you may save the embeddings into numpy files and then visualize tsne plots.

**Comment by tahmine88** [comment]
thanks for your response, is there any code or pseudo-code for it?

**Comment by curiosity654** [comment]
> thanks for your response, is there any code or pseudo-code for it?

I think it's simply saving the features before the last layer of your network and visualize them with tsne.

**Comment by curiosity654** [comment]
> thanks for your response, is there any code or pseudo-code for it?

I think it's simply saving the features before the last layer of your network and visualize them with tsne.

**Comment by mohammad9975** [comment]
thanks
they are 2D features, do you turn them into a vector then visualize it?! I don't think so! so how do you do that?

**Comment by curiosity654** [comment]
What do you mean by 2D features? If it's an H*W 2D feature map with D feature dimensions, then you just flatten them into N*D feature vector, here N=H*W, and feed it into the API together with labels.

**Comment by mohammad9975** [comment]
thank you so much, I think I got it.

**Comment by jiangzhengkai** [comment]
@tfzhou would you mind sharing the color for the tsne embedding?
