### ISSUE TITLE
Code/main_contrastive.py

### ISSUE THREAD

**Issue by VivianBB** [tfzhou/ContrastiveSeg#13]
Hi, Dr.Zhou.
Sorry to bother you, but could you please give an example to conduct the command file?
Considering various version of bash files, it would be nice to give an description about your naming style. 
For example, (1) "run_ideal_spatial_ocrnet.sh", "xxx_ideal_gather_ocrnet.sh", and "xxx_ideal_distribute_octnet.sh"
(2) "run_ideal_spatial_ocrnet.sh", "run_ideal_spatial_ocrnet_b.sh", and "run_ideal_spatial_ocrnet_c.sh"

Thank you, and looking forward to your reponse.

**Comment by VivianBB** [comment]
Hey, it's Vivian again. I started shell script yesterday, and figured out how the "main/main_contrastive.py" works. 
Still:
(1) I am not sure about "xxxx_b.py"/"xxxx_c.py".
(2) AND will you soon release the bash of ORCNet-based scripts and checkpoints which behaved best in your paper (83.2 on train and 82.4 on train_val, Cityscape)?

**Comment by tfzhou** [comment]
Hi, please refer to the files with names "job_xxxx.sh", which show how to start training. For more training and inference details, please also refer to the original OpenSeg repo.
