### ISSUE TITLE
implementation of memory bank?

### ISSUE THREAD

**Issue by jiangzhengkai** [tfzhou/ContrastiveSeg#15]
Hi, thanks for your great work. Will you update the code for the memory bank?

**Comment by lorenmt** [comment]
Hello, maybe you want to check out my project: https://github.com/lorenmt/reco, which is a parallel work developed roughly at the same time as for this paper, with a similar motivation on applying regional-based contrastive learning method for semantic segmentation tasks. But different from this paper, my work is more focused on semi-supervised learning. :)

**Comment by tfzhou** [comment]
Thanks for your interest. Now I have updated the codes. I will close this, but feel free to reopen if you have more questions.
