### ISSUE TITLE
Problem in contrastive loss

### ISSUE THREAD

**Issue by Jarvis73** [tfzhou/ContrastiveSeg#16]
Hi, Dr. Zhou,

Thanks for releasing the code. When reading the code about the contrastive loss in function `_contrastive()`, a `mask` is computed by following two lines:
https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L124
and
https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L131

Now I think the shape of the `mask` is `[anchor_num * anchor_count, class_num * cache_size]`. If I did not misunderstand the code, the `mask` is a 'positive' mask, and each line represents the positive samples of an anchor view. 

Then in L134-L138, the function of `logits_mask` is confusing:
https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L134-L138
Could you please explain these lines? 

Suppose I have anchor_num=6 (2 images, 3 valid classes per image), anchor_count=2 (sample two pixels per class), class_num=5 (class number), cache_size=2 (memory size), then the following code raises RuntimeError:

```python
mask = torch.ones((6 * 2, 5 * 2)).scatter_(1, torch.arange(6 * 2).view(-1, 1), 0)
```
Output:
```
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
RuntimeError: index 10 is out of bounds for dimension 1 with size 10
```

**Comment by FeiYuejiao** [comment]
Same question here. Can anyone explain why the masks and logits are formed like this?

**Comment by wangbo-zhao** [comment]
why we use logits_mask = torch.ones_like(mask).scatter_(1, 
                                              torch.arange(anchor_num * anchor_count).view(-1, 1).cuda(), 
                                              0)

**Comment by eezywu** [comment]
> why we use logits_mask = torch.ones_like(mask).scatter_(1,
> torch.arange(anchor_num * anchor_count).view(-1, 1).cuda(),
> 0)

I think the purpose is to ignore the similarity of the feature itself.

**Comment by edwardpwtsoi** [comment]
> why we use logits_mask = torch.ones_like(mask).scatter_(1,
> torch.arange(anchor_num * anchor_count).view(-1, 1).cuda(),
> 0)

Actually it is equivalent to fill_diagonal_ method with 0

**Comment by edwardpwtsoi** [comment]
> Hi, Dr. Zhou,
> 
> Thanks for releasing the code. When reading the code about the contrastive loss in function `_contrastive()`, a `mask` is computed by following two lines:
> 
> https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L124
> 
> 
> and
> https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L131
> 
> Now I think the shape of the `mask` is `[anchor_num * anchor_count, class_num * cache_size]`. If I did not misunderstand the code, the `mask` is a 'positive' mask, and each line represents the positive samples of an anchor view.
> 
> Then in L134-L138, the function of `logits_mask` is confusing:
> 
> https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L134-L138
> 
> 
> Could you please explain these lines?
> Suppose I have anchor_num=6 (2 images, 3 valid classes per image), anchor_count=2 (sample two pixels per class), class_num=5 (class number), cache_size=2 (memory size), then the following code raises RuntimeError:
> 
> ```python
> mask = torch.ones((6 * 2, 5 * 2)).scatter_(1, torch.arange(6 * 2).view(-1, 1), 0)
> ```
> 
> Output:
> 
> ```
> Traceback (most recent call last):
>     File "<stdin>", line 1, in <module>
> RuntimeError: index 10 is out of bounds for dimension 1 with size 10
> ```
As of my knowledge, the line

https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L124

can be view as an indicator function of pixel_i == pixel_j for i, j in N (Number of samples including mini batch and mem bank)

The repeat here is because the shape of the anchors are (num_classes, num_views, feature_dim). So, the labels after unbind would alternating. for example, you have [0, 1, 2] and 2 views per classes your labels would become [0, 1, 2, 0, 1, 2] instead of [0, 0, 1, 1, 2, 2]

https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast_mem.py#L131

the dimension of the mask is (anchor_num * anchor_count + contrast_class * contrast_count, anchor_num * anchor_count + contrast_class * contrast_count)

so, if in your case, the above code should be modified to

```python
mask = torch.ones((6 * 2 + 5 * 2, 6 * 2 + 5 * 2)).scatter_(1, torch.arange(6 * 2 + 5 * 2,).view(-1, 1), 0)
```

Correct me if I make mistake :)

**Comment by HenryPengZou** [comment]
Same question here, could you help explain why the masks and logits are formed like this? @tfzhou

**Comment by Xxxxiahaofeng** [comment]
I have another question about function `_contrastive()`.
What's the purpose of 
```
logits_max, _ = torch.max(anchor_dot_contrast, dim=1, keepdim=True)  
logits = anchor_dot_contrast - logits_max.detach()
```
If `size` of `anchor_dot_contrast` is `[800, 800]`, then logits_max is the diagonal elements of `anchor_dot_contrast` with shape `[800, 1]`. So the subtraction means every column of `anchor_dot_contrast` has to be subtracted by  `logits_max`.

**Comment by xianxuan-z** [comment]
I finally find partners here，I have a question.
What does the args “n_views” mean in Contrastive loss?Can you show me an example?

**Comment by tfzhou** [comment]
Thanks for the questions! @Jarvis73 L134-138 is to remove self-contrastive. @Xxxxiahaofeng, the purpose to remove ```logits_max``` is for numerical stability. It is not necessary.

**Comment by purse1996** [comment]
> 

I agree with your opinion. I think 
when queue is None, 
logits_mask = torch.ones_like(mask).scatter_(1,
                                                        torch.arange(anchor_num * anchor_count).view(-1, 1).cuda(),
                                                        0)

**Comment by crisz94** [comment]
> Thanks for the questions! @Jarvis73 L134-138 is to remove self-contrastive. @Xxxxiahaofeng, the purpose to remove `logits_max` is for numerical stability. It is not always necessary.

hi @tfzhou , I think self-contrastive only exists when queue==None.
