### ISSUE TITLE
Problem in the function "_dequeue_and_enqueue"

### ISSUE THREAD

**Issue by eezywu** [tfzhou/ContrastiveSeg#18]
Hello, 
I have one problem at the code `pixel_queue_ptr[lb] = (pixel_queue_ptr[lb] + 1) % self.memory_size` in the line 138, `_dequeue_and_enqueue` function, trainer_contrastive.py file. Should `pixel_queue_ptr[lb] + 1` be modified to `pixel_queue_ptr[lb] + K`? Otherwise, `pixel_queue[lb, ptr + 1:ptr + 1 + K, :] ` will be assigned at the next iteration, which is overlapped with `pixel_queue[lb, ptr:ptr + K, :]`.

**Comment by wangbo-zhao** [comment]
I find the same problem
