### ISSUE TITLE
Potentially a bug in hard anchor sampling

### ISSUE THREAD

**Issue by edwardpwtsoi** [tfzhou/ContrastiveSeg#19]
on line 30

https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast.py#L30

on line  144

https://github.com/tfzhou/ContrastiveSeg/blob/2ab84d8ec679adc7f7be1853c8684b44bf899273/lib/loss/loss_contrast.py#L144

Should the y_hat actually be prediction from model in stead of target from label?

**Comment by tfzhou** [comment]
Hi, here `y_hat` should refer to the ground-truth labels.
