### ISSUE TITLE
tSNE visualisation

### ISSUE THREAD

**Issue by YuemingJin** [tfzhou/ContrastiveSeg#26]
Hi,

Thanks for your great work! I am wondering how you select feature embeddings for tSNE visualisation? Because for the dense pixel-level segmentation task, if we use feature embeddings of all the pixels, it will be too much.

Many thanks!

**Comment by tfzhou** [comment]
Yes, using all pixels is not necessary. Instead, you can sample a small number of pixels for tsne visualization.
