### ISSUE TITLE
network_stride &  _dequeue_and_enqueue

### ISSUE THREAD

**Issue by Darcy103** [tfzhou/ContrastiveSeg#28]
Thank you very much for your excellent work, I have a few questions to consult you.
1. What is the function of this parameter **_network_stride_**, and why do you perform this operation on the labels?

2. I want to know what are the dimensions of the two parameters(keys, labels) passed by the function _**_dequeue_and_enqueue,**_ and are they the same?

3. Can your code handle segmentation tasks with labels starting from 0? I didn't understand the statement _**this_label_ids = [x for x in this_label_ids if x > 0]**_ in the function _**_dequeue_and_enqueue**_

**Comment by oliverester** [comment]
+1 for the **network_stride**. I think the idea is to align the labels and keys dimensions. However, for me, the alignment does not work.

For 2. the labels dimensions is of the size of the original masks. The keys are of the size of the backbone feature embeddings which may vary depending on the backbone (ResNet, HRNet)

For 3. Label id 0 is excluded everywhere in the code. You have to find the parts and change the code - or maybe you can create a dummy class 0 which does not exist in your masks?

**Comment by Darcy103** [comment]
Thanks for your reply.
