### ISSUE TITLE
Repo based on pytorch==0.4.x ?

### ISSUE THREAD

**Issue by TiankaiHang** [tfzhou/ContrastiveSeg#3]
Thanks for your nice work!
Repo based on pytorch==0.4.x ?

And also, how about the FLOPs (computation) of your method?

**Comment by tfzhou** [comment]
Hi, thanks for your interest! 

We use PyTorch 0.4.1. For the FLOPs, our approach only introduces a small projection head over base models during training, therefore, the increased FLOPs is minor. For inference, its FLOPs will be exactly same to base models.
