### ISSUE TITLE
论文相似

### ISSUE THREAD

**Issue by nlp-tokio** [tfzhou/ContrastiveSeg#30]
似乎有一篇论文Region-aware Contrastive Learning for Semantic Segmentation疑似抄袭你们的成果

**Comment by tfzhou** [comment]
@nlp-tokio 感谢你的提醒。我们的文章是2021年1月28号上传到arXiv上的，并同时开源了代码，在2月23号也被机器之心进行了宣传。你指出的这篇文章与我们的文章极度相似，不论是idea，部分论文描述，甚至Figure都有模仿我们文章的痕迹。对此，我们也十分的震惊。我们会尽力弄清楚这件事情，再次感谢你的提醒。
