### ISSUE TITLE
About simple reproduction

### ISSUE THREAD

**Issue by xianxuan-z** [tfzhou/ContrastiveSeg#34]
Hello,  there are too many files in the project, I would like to ask you if I just want to try to reproduce the simple results of the camvid dataset combined with the pixel contrast learning method, what should I go to see about model creation, loss function, What about the data preprocessing, and the .py files and .sh files for training and testing?
I hope you can take the time to give me some simple guidelines, which will benefit me a lot, thank you!

**Comment by tfzhou** [comment]
Hi @xianxuan-z , very good suggestion. However, I am sorry that I will not have too much time for this. It will be great if you can do this thing, and I also can provide supports for possible issues.
