### ISSUE TITLE
why ignore zero?

### ISSUE THREAD

**Issue by Junshan233** [tfzhou/ContrastiveSeg#35]
Hi, thanks for your outstanding work.
I have a question when researching your code. 
Why ignore it when class id equals zero?

https://github.com/tfzhou/ContrastiveSeg/blob/7be326ae9127a847558584eac489d4858adf7cb1/lib/loss/loss_contrast_mem.py#L98

https://github.com/tfzhou/ContrastiveSeg/blob/7be326ae9127a847558584eac489d4858adf7cb1/segmentor/trainer_contrastive.py#L114

**Comment by dongdongtong** [comment]
Same question.
If the code ignore 0 class, this line will raise zero-division exception because there is no positive samples with 0 class:

>         mean_log_prob_pos = (mask * log_prob).sum(1) / mask.sum(1)

**Comment by dongdongtong** [comment]
Same question.
If the code ignore 0 class, this line will raise zero-division exception because there is no positive samples with 0 class:

https://github.com/tfzhou/ContrastiveSeg/blob/7be326ae9127a847558584eac489d4858adf7cb1/lib/loss/loss_contrast_mem.py#L147

**Comment by Junshan233** [comment]
Another question,
Why is the step size of `pixel_queue_ptr` is 1 instead of `K`?
https://github.com/tfzhou/ContrastiveSeg/blob/7be326ae9127a847558584eac489d4858adf7cb1/segmentor/trainer_contrastive.py#L138
Thanks.

**Comment by tfzhou** [comment]
Hi @Junshan233 @Junshan233 , in my cases, the datasets only include a number of semantic categories and one class that will be ignored. Thus, it is ok to ignore class `0`. If this does not works in your cases, you need to change the code. For the pointer issue, please refer to https://github.com/tfzhou/ContrastiveSeg/issues/18.
