### ISSUE TITLE
Questions about T-SNE visualization

### ISSUE THREAD

**Issue by dongdongtong** [tfzhou/ContrastiveSeg#36]
Hello, Nice work. 
I am curious about how to visualize embeddings on a 2D plot with t-sne, and where the embeddings come from.

The 1st question is about the embedding collection. Specifically, there are two ways collecting embeddings from images(or feature maps).
- collect embeddings  from only one val image or val images in a single mini batch.
- construct a memory bank  to collect feature pixels across all val images, then randomly select N samples as t-sne inputs.

Next question is that the embeddings collected above come from the output of last conv layer before the classifier or the MLP projection head?

**Comment by tfzhou** [comment]
The pixel embeddings are randomly selected from multiple testing images. Features after the projection layer are used, on which the contrastive loss is directly imposed.

**Comment by dongdongtong** [comment]
Thanks for your reply.

**Comment by lennart-maack** [comment]
Why did you choose to use the features after the projection layer and not the features from the embedding space (after the encoder)?
Isn't the goal to cluster together the feature embeddings in the latent space from the same pixel class to make the downstream task of segmentation of the decoder easier? During inference, the projection layers are not used anyway
