### ISSUE TITLE
Dimension of feature embedding + full_res_stem

### ISSUE THREAD

**Issue by oliverester** [tfzhou/ContrastiveSeg#39]
Dear @tfzhou ,

I find your work really interesting - thanks a lot (also to your team).
In your paper you state that you use an
![image](https://user-images.githubusercontent.com/11405884/148406858-0307b1e0-980a-46d6-9a9d-a97c8e84dafe.png)

Using the HRNet backbone I need to set the `full_res_stem` env variable to get an embedding of the same dimension as the input image. Else, there is an interpolation logic to upsample the feature-embeddings, which seems to happen for any use of the ResNet backbone.

I was wondering if you use the `full_res_stem` env variable for your stated results? Also, did you observe a performance difference when the feature embedding dimensions < input dimensions?

Thanks
Oliver

**Comment by tfzhou** [comment]
@oliverester Thanks your interest. I did not remember that I used the variable `full_res_stem`. For HRNet, the feature (spatial) dimension is 1/4 the size of the input image, which is same as the resnet backbone (with dilated convolutions).
