### ISSUE TITLE
About memory bank

### ISSUE THREAD

**Issue by hzhupku** [tfzhou/ContrastiveSeg#7]
Thank you for your code. But I can not find the implementations of memory bank. How do you realize the contrastive loss?

**Comment by tfzhou** [comment]
Thanks for your interest. The code of memory bank will be provided upon paper acceptance. The contrastive loss (over each batch) code can be found at:
https://github.com/tfzhou/ContrastiveSeg/blob/9a381b9799c16d81e18d8f9f25ab509b93fb56de/lib/loss/loss_contrast.py#L91.
