### ISSUE TITLE
About contrastive loss function

### ISSUE THREAD

**Issue by ChoiDM** [tfzhou/ContrastiveSeg#8]
Hi, thank you for the amazing work!
Your paper and concept are really interesting.

I have trouble understanding your contrastive loss function in [here](https://github.com/tfzhou/ContrastiveSeg/blob/main/lib/loss/loss_contrast.py#L91).
What should be the input of this ```_contrastive``` function? 

In other words, would you let me know
1) which variable should I pass as ```feats_``` and ```labels_``` and 
2) how should their shapes be? (ex. ```number of anchors X number of views```

**Comment by tfzhou** [comment]
Hi,

Please refer to the following two lines for the shapes of tensors https://github.com/tfzhou/ContrastiveSeg/blob/9a381b9799c16d81e18d8f9f25ab509b93fb56de/lib/loss/loss_contrast.py#L50-L51
